name: CI

on:
  push:
    tags:
    - v*
    branches:
    - main
  pull_request:
    branches:
    - main
    paths:
    - MaterialColorUtilities**
    - .github/workflows/ci.yml

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'MaterialColorUtilities.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get Build Version
      run: |
        Import-Module .\.github\workflows\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v2.0.0
      with:
        dotnet-version: 6.0.x

    - name: Restore .NET workloads
      run: dotnet workload restore

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

    - name: Run tests
      run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal
      
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}